-- =========================================================
-- V1: create all tables for PetsHotel
-- Generated from the JPA entities, then organised by hand.
-- Enum columns are stored as text (EnumType.STRING).
-- =========================================================

-- ---------- users ----------
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name    VARCHAR(255) NOT NULL,
    last_name     VARCHAR(255) NOT NULL,
    email         VARCHAR(255) NOT NULL,
    password      VARCHAR(255) NOT NULL,
    phone_number  VARCHAR(255) NOT NULL,
    role          VARCHAR(255) NOT NULL,
    active        BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_users_email UNIQUE (email),
    CONSTRAINT ck_users_role CHECK (role IN ('CUSTOMER', 'STAFF', 'ADMIN'))
);

-- ---------- rooms ----------
CREATE TABLE rooms (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    room_number              VARCHAR(255)  NOT NULL,
    name                     VARCHAR(255)  NOT NULL,
    description              VARCHAR(255),
    capacity                 INTEGER       NOT NULL,
    price_per_pet_per_night  NUMERIC(10,2) NOT NULL,
    status                   VARCHAR(255)  NOT NULL,
    image_url                VARCHAR(500),
    CONSTRAINT uk_rooms_room_number UNIQUE (room_number),
    CONSTRAINT ck_rooms_status CHECK (status IN ('ACTIVE', 'INACTIVE', 'MAINTENANCE')),
    CONSTRAINT ck_rooms_capacity CHECK (capacity >= 1),
    CONSTRAINT ck_rooms_price CHECK (price_per_pet_per_night >= 0)
);

-- ---------- pets ----------
CREATE TABLE pets (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    owner_id             BIGINT       NOT NULL,
    name                 VARCHAR(255) NOT NULL,
    type                 VARCHAR(255) NOT NULL,
    breed                VARCHAR(255),
    age                  INTEGER,
    weight               DOUBLE PRECISION,
    gender               VARCHAR(255),
    medical_note         VARCHAR(255),
    feeding_instruction  VARCHAR(255),
    special_note         VARCHAR(255),
    image_url            VARCHAR(255),
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    CONSTRAINT fk_pets_owner FOREIGN KEY (owner_id) REFERENCES users (id),
    CONSTRAINT ck_pets_type CHECK (type IN ('DOG', 'CAT', 'OTHER'))
);

-- ---------- promotions ----------
CREATE TABLE promotions (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(255)  NOT NULL,
    description     TEXT,
    type            VARCHAR(255)  NOT NULL,
    value           NUMERIC(10,2) NOT NULL,
    start_date      DATE,
    end_date        DATE,
    minimum_nights  INTEGER,
    active          BOOLEAN       NOT NULL DEFAULT TRUE,
    CONSTRAINT ck_promotions_type CHECK (type IN ('PERCENTAGE', 'FIXED_AMOUNT'))
);

-- ---------- extra_services ----------
CREATE TABLE extra_services (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255)  NOT NULL,
    description  TEXT,
    price        NUMERIC(10,2) NOT NULL,
    active       BOOLEAN       NOT NULL DEFAULT TRUE
);

-- ---------- bookings ----------
CREATE TABLE bookings (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT        NOT NULL,
    room_id           BIGINT        NOT NULL,
    promotion_id      BIGINT,
    check_in_date     DATE          NOT NULL,
    check_out_date    DATE          NOT NULL,
    status            VARCHAR(255)  NOT NULL,
    room_amount       NUMERIC(10,2),
    service_amount    NUMERIC(10,2),
    surcharge_amount  NUMERIC(10,2),
    discount_amount   NUMERIC(10,2),
    total_price       NUMERIC(38,2),
    promotion_name    VARCHAR(255),
    payment_status    VARCHAR(255)  NOT NULL DEFAULT 'UNPAID',
    paid_amount       NUMERIC(10,2),
    paid_at           TIMESTAMP(6),
    created_at        TIMESTAMP(6)  NOT NULL,
    CONSTRAINT fk_bookings_user      FOREIGN KEY (user_id)      REFERENCES users (id),
    CONSTRAINT fk_bookings_room      FOREIGN KEY (room_id)      REFERENCES rooms (id),
    CONSTRAINT fk_bookings_promotion FOREIGN KEY (promotion_id) REFERENCES promotions (id),
    CONSTRAINT ck_bookings_status CHECK (status IN ('PENDING', 'CONFIRMED', 'CHECKED_IN', 'CHECKED_OUT', 'CANCELLED')),
    CONSTRAINT ck_bookings_payment_status CHECK (payment_status IN ('UNPAID', 'PAID')),
    CONSTRAINT ck_bookings_dates CHECK (check_out_date > check_in_date)
);

-- ---------- booking_pets (Many-to-Many: bookings <-> pets) ----------
CREATE TABLE booking_pets (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id  BIGINT NOT NULL,
    pet_id      BIGINT NOT NULL,
    CONSTRAINT fk_booking_pets_booking FOREIGN KEY (booking_id) REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_booking_pets_pet     FOREIGN KEY (pet_id)     REFERENCES pets (id)
);

-- ---------- booking_extra_services (Many-to-Many: bookings <-> extra_services) ----------
CREATE TABLE booking_extra_services (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        BIGINT        NOT NULL,
    extra_service_id  BIGINT        NOT NULL,
    booking_pet_id    BIGINT,
    quantity          INTEGER       NOT NULL,
    unit_price        NUMERIC(10,2) NOT NULL,
    total_price       NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_bes_booking       FOREIGN KEY (booking_id)       REFERENCES bookings (id) ON DELETE CASCADE,
    CONSTRAINT fk_bes_extra_service FOREIGN KEY (extra_service_id) REFERENCES extra_services (id),
    CONSTRAINT fk_bes_booking_pet   FOREIGN KEY (booking_pet_id)   REFERENCES booking_pets (id)
);

-- ---------- receipts (One-to-One with bookings) ----------
CREATE TABLE receipts (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_id        BIGINT        NOT NULL,
    receipt_number    VARCHAR(255)  NOT NULL,
    issued_at         TIMESTAMP(6)  NOT NULL,
    room_amount       NUMERIC(10,2),
    service_amount    NUMERIC(10,2),
    surcharge_amount  NUMERIC(10,2),
    discount_amount   NUMERIC(10,2),
    total_amount      NUMERIC(10,2) NOT NULL,
    CONSTRAINT fk_receipts_booking FOREIGN KEY (booking_id) REFERENCES bookings (id),
    CONSTRAINT uk_receipts_booking UNIQUE (booking_id),
    CONSTRAINT uk_receipts_number  UNIQUE (receipt_number)
);

-- ---------- daily_care_reports ----------
CREATE TABLE daily_care_reports (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    booking_pet_id   BIGINT       NOT NULL,
    recorded_by_id   BIGINT       NOT NULL,
    report_date      DATE         NOT NULL,
    feeding_morning  VARCHAR(255),
    feeding_evening  VARCHAR(255),
    walking_minutes  INTEGER,
    grooming         VARCHAR(255),
    mood             VARCHAR(255),
    health_note      VARCHAR(255),
    general_note     VARCHAR(255),
    created_at       TIMESTAMP(6) NOT NULL,
    CONSTRAINT fk_care_reports_booking_pet FOREIGN KEY (booking_pet_id) REFERENCES booking_pets (id),
    CONSTRAINT fk_care_reports_recorded_by FOREIGN KEY (recorded_by_id) REFERENCES users (id),
    CONSTRAINT uk_care_report_booking_pet_date UNIQUE (booking_pet_id, report_date)
);

-- =========================================================
-- Indexes
-- PostgreSQL indexes PRIMARY KEY and UNIQUE columns automatically,
-- but not FOREIGN KEY columns, so the common lookups are added here.
-- =========================================================

-- pets of one owner (My Pets page, booking form)
CREATE INDEX idx_pets_owner_id ON pets (owner_id);

-- bookings of one customer (My Bookings page)
CREATE INDEX idx_bookings_user_id ON bookings (user_id);

-- room availability: overlapping bookings of a room in a date range
CREATE INDEX idx_bookings_room_dates ON bookings (room_id, check_in_date, check_out_date);

-- staff booking list filtered by status
CREATE INDEX idx_bookings_status ON bookings (status);

-- pets in a booking, and bookings that contain a pet (overlap check)
CREATE INDEX idx_booking_pets_booking_id ON booking_pets (booking_id);
CREATE INDEX idx_booking_pets_pet_id ON booking_pets (pet_id);

-- extra services of a booking (price and receipt)
CREATE INDEX idx_bes_booking_id ON booking_extra_services (booking_id);

-- reports written by a staff member
CREATE INDEX idx_care_reports_recorded_by ON daily_care_reports (recorded_by_id);